name: build-and-test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        working-directory: ./backend
        run: npm install

      - name: Vérifier la qualité du code (lint)
        working-directory: ./backend
        run: npm run lint

      - name: Build du projet
        working-directory: ./backend
        run: npm run build

      - name: Exécuter les tests
        working-directory: ./backend
        run: npm test

